### PR TITLE
Accessibility Update: add aria-hidden attribute to hidden input

### PR DESCRIPTION
**Pull request by christopher-bio**

### CODE REVIEW

**Comment by dennisnissle** [comment]
Hi @christopher-bio,

thanks for your pull request. Could you clarify on why you want the id of the hidden (Woo core) terms checkbox to equal the checkbox id added by Germanized? I see some issues with JS here.

**Comment by christopher-bio** [comment]
Thanks a lot for looking at this @dennisnissle.

I am sorry, at least on my implementation I did not have the same "legal" ID from Woo Core. The reason for adding the ID is that the input at the moment comes without a label and that the label (at least on my end) does not have an input + that the label matches the input perfectly.

**Comment by dennisnissle** [comment]
`legal` is the default id for the general checkbox introduced by Germanized: https://github.com/vendidero/woocommerce-germanized/blob/master/includes/class-wc-gzd-legal-checkbox-manager.php#L141

Whether the checkbox comes without an actual checkbox, depends on your settings. Germanized adds this hidden checkbox for compatibility purposes only to mimic the Woo core behaviour.

**Comment by christopher-bio** [comment]
I have removed it and would be anyway satisfied with aria-hidden already.

**Comment by dennisnissle** [comment]
LGTM! Thanks!

**Pull request merged**
