### PR TITLE
Subscriptions & Recurring Mandate Support

### PR DESCRIPTION
**Pull request by holzhannes**
- feature: support for subscriptions invoice payments
- feature: support for subscriptions direct-debit payments
- feature: support for recurring mandate
	- If a user account is created during checkout a recurring mandate will be generated, bank account details will be stored enrypted in the users meta together with the recurring mandate (ID, DateOfSig & SigMail).
	- If a logged in user, with existing recurring mandate is buying something, this existing mandate will be used if bank account details (Holder, IBAN, BIC) did not change
	- If the bank account details have changed, a new recurring mandate is generated. In user meta is stored for each value (owner, IBAN, BIC) when it was last modified.
	- If no user account is created or exiting during checkout a single mandate will be generated like in earlier times

- feature: live mandate preview will show if recurring mandate or single payment mandate will be used
- feature: live mandate preview will show existing recurring mandate id and details
- feature: export filter (only unpaid)

### CODE REVIEW

**Comment by vendidero** [comment]
Hi,

thank you for taking care of the subscription issue. We have already put some thoughts into that issue before and didn't take steps to support subscriptions yet because of some legal barriers. Did you think of pre notifications or do you know how that can be handled? Should that be handled by the shop?

cheers

**Comment by holzhannes** [comment]
Hi, this pull request does not yet include pre notification. I am doing this with the [Follow Ups Plugin](https://woocommerce.com/products/follow-up-emails/), but of course it would be a good Idea to include this in Germanized. For my pre notification I am using this german text. I will check if it is possible to include pre notification directly into WooCommerce Germanized.

```
Sehr geehrter Kunde, 

für das bei uns gebuchte Produkt <strong>{item_name}</strong> werden wir ab dem {subs_renew_date} den Betrag von {subs_cost} von dem bei uns hinterlegten Konto abbuchen.

Mit freundlichem Gruß

XYZ

--
Dieser Hinweis ist gesetzlich vorgeschrieben und kann nicht abstellt werden.
```

**Comment by vendidero** [comment]
Hi,

I think we have 2 options here:

1. Include a default text within the order confirmation email noticing the account owner:
"Within the next 14 days we will debit your account..." - the amount of days could be an option within the gateway settings.

2. Separate email template for pre-notifications. This option would be a little bit more complicated because we would have to either manually or automatically send the pre-notification e.g. when updating the order status to a certain value. 

Which option do you suggest? 

Btw: You are using wcs_order_contains_subscription (https://github.com/holzhannes/woocommerce-germanized/blob/4e08a0166566d6336a27728f07d48d3e8a8f3685/includes/gateways/direct-debit/class-wc-gzd-gateway-direct-debit.php#L565) - this function may not exist for users who are not having the subscription plugin enabled.

**Comment by vendidero** [comment]
Hi,

we did already prepare an implementation for plugin-compatilities. Would be superb if you could implement the compatibility for Subscriptions the same way e.g.:

woocommerce-germanized/includes/compatibility/class-wc-gzd-compatibility-woocommerce-subscriptions.php

Just add a new filter e.g. "woocommerce_gzd_direct_debit_mandate_type_text" which you can then adjust within the compatibility class (just add the filter via add_filter to the load method).
The filter should be of course implemented in the direct debit gateway class as well via apply_filters e.g.

```php
public function get_mandate_type_text( $order , $create_user) {
    return apply_filters( 'woocommerce_gzd_direct_debit_mandate_type_text', __( 'a single payment', 'woocommerce-germanized' ), $order, $create_user );
}
```

I could implement that as well if you don't have time to do it - just tell me :)

**Comment by holzhannes** [comment]
Hi,

thank you very much for supporting me, at moment I am getting lost a little bit. If you have time I would be happy if you could implement it :-). I think you also have write access to my branch.

For the moment I think we should use option 1 because it has less possible errors and less mails to customer:
*Include a default text within the order confirmation email noticing the account owner: "Within the next 14 days we will debit your account..." - the amount of days could be an option within the gateway settings.*

We just have to check that in the exported XML-File we use the next_payment_date + pre_notify_period as payment date. 

Thank you very much

**Comment by vendidero** [comment]
Hi there,

please see my latest commit:
https://github.com/vendidero/woocommerce-germanized/commit/4fdb662cc5090cf0b5392b2914a147b93ca1ad6a

I've added/changed some features and moved the compatibility to the Subscriptions compatibility class. Feel free to test :)

Cheers

**Comment by holzhannes** [comment]
Hi, 

Thank you very much for you Commit and Work. If have tested your commit [4fdb662](https://github.com/vendidero/woocommerce-germanized/commit/4fdb662cc5090cf0b5392b2914a147b93ca1ad6a) here are some things I have noticed. 

1. SEPA-Export-File is including the Subscription and the Order therefore the customer would pay the double price ;-). Only the Order should be included. Happens through old & new SEPA-Export-Button.
2. Every order placed for a customer with recuring mandate-ID will create a new mandate-ID instead of using the exiting mandate-ID. Maybe it is a good idea to store the recuring SEPA mandate-ID together with date of signing within the user meta, because they are needed for processing the next SEPA-Mandate E-Mail at the time of a new order and for exporting the SEPA-XML-File. 
3. Pre-Notification-Period should be added to the (First) SEPA-Mandate send to the Customer via E-Mail
4. Subscriptions are not set to automatic payment for recuring payments, they are all set to manual renewal.
5. If a create a manual renewal this renewal order does not have any payment data.
6. Note: Since november 2016 „FRST“ (First) is optional and not needed. The first one should also use „RCUR“ (Recurrent).

In case you need a copy of WooCommerce Subscriptions just ask me.

**Comment by holzhannes** [comment]
Maybe Interesting as well: 
- [WooCommerce Germanized SEPA Profile Fields for Admins](https://github.com/holzhannes/woocommerce-germanized-sepa-fields-for-admins)
- [WooCommerce Germanized Extended SEPA Export Usage Value](https://github.com/holzhannes/woocommerce-germanized-extended-sepa-usage)

**Comment by vendidero** [comment]
Hi,

1. Allright, I'll check that again. What do you suggest as export "standard" option for subscriptions? If exporting a subscription, which orders should be included? E.g. the subscription has been renewed for two times - that's why there are 3 orders (initial, renew, renew). The first order and the first renewal has already been paid/completed. When exporting the subscription only the latest, pending renewal order should be exported? Or what do you suggest?
2. I think we should stick to the "one-mandate-per-subscription" idea and not generate a recurring mandate for multiple order/subscriptions on a per-user-base. 
3. Hm, allright. So that would be a pre-notification being sent only once per subscription.
4. Do you know how to mark a payment gateway as being able to automatically process renewals? I couldn't find some definite information about that in the docs.
5. I'll need to check that too.
6. Ok, will change that.

Could you send the latest version to info@vendidero.de? That'd be great!

Cheers

**Comment by holzhannes** [comment]
Hallo Dennis, ich mache mal auf Deutsch weiter ;-)

1. Aus meiner Sicht sollte(n) nur die Bestellung(en) im Export enthalten sein, welche noch nicht bezahlt wurden. Im Export sollte **nie die Subscription enthalten sein**, sondern immer nur die einzelnen Bestellungen. Die Subscription selbst ist ja nur ein Hilfsobjekt mit den Metadaten des Abos. Momentan (ohne Subscription support) kann man für jede Bestellung eine einzelne XML-Datei exportieren (per Button) oder man geht über Werkzeuge --> Daten-Exportieren --> Lastschriften und wählt einen Zeitraum. Da hier auch bereits bezahlte Bestellungen wieder im Export waren, hatte ich die Funktion eingebaut, um nur unbezahlte zu exportieren, wobei es eigentlich keinen Sinn macht bereits bezahlte Bestellungen mit in den Lastschrift-Export mit aufzunehmen.

2. Das halte ich leider für etwas unübersichtlich. Aus meiner Sicht sollte ein Kunde bei mir im Shop entweder viele **Einzelmandate** erteilen wenn er **kein Kundenkonto hat** und eine **wiederkehrendes Mandat** wenn er **ein Kundenkonto und/oder Abos hat**. Abos ohne Kundenkonto sind irgendwie nicht sinnvoll. Es ist wenig hilfreich für einen Kunden verschiedene Mandate zu haben wenn dieser mehrere Abos hat. Ein Mandat je Benutzerkonto hilft den Shopbetreibern welche z.B. schon ein wiederkehrendes SEPA-Mandat des Kunden haben (z. B. in Papierform) und dieses im Shop hinterlegen können. Auch gibt es beim Ansatz von ein Mandat je Abo ein Problem wenn der Benutzer seine Bankverbindung ändert, da dann alle Mandate erneuert werden müssen und der Kunde auf einen Schlag viele neue Mandate per E-Mail bekommt. Auch ist es aus meiner Sicht wichtig den genauen Zeitpunkt und die E-Mail-Adresse zum Zeitpunkt der Erstellung des Mandates in den Benutzerdaten zu speichern, sodass man gegenüber der Bank einen Nachweis hat wann der Benutzer das Mandat erteilt hat. 
_Ein Super Feature für später wäre dann natürlich noch die Möglichkeit das Mandate per Button Manuell an den Kunden und/oder Admin als PDF fürs Archiv zu schicken._
Ich hoffe ich konnte dir den Ansatz für nur genau ein wiederkehrendes Mandat je Kunde etwas schmackhafter machen. :-)
3. Hier meinte ich mehr die Vorabinformation sollte auch schon im ersten SEPA-Mandat oder in der ersten Bestellbestätigung enthalten sein. Momentan steht im SEPA-Mandat noch wird auf einen Tag verkürzt.
4. Da muss ich nochmal schauen wie das in meinem Code war. Ist aber in jedem Fall nicht kompliziert.

Plugin kommt dann in Kürze per Mail.

Viele Grüße holzhannes

**Pull request closed without merging**
