### PR TITLE
Install PHPUnit-compat the Composer way

### PR DESCRIPTION
**Pull request by szepeviktor**
Let's give it a try! 🚀

### CODE REVIEW

**Comment by dennisnissle** [comment]
Hi there,

what is the advantage of changing code that is currently working perfectly? Please elaborate.

Best,
Dennis

**Comment by szepeviktor** [comment]
No, there is not advantage.
It is smaller and make composer work.

**Comment by szepeviktor** [comment]
Actually there is: I'm learning GHA and Composer internals.

**Comment by szepeviktor** [comment]
@dennisnissle If you are interested here is how use Composer only for PHPUnit-compat.

```yml
      - name: Composer install
        run: |
          composer config github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}
          composer install
      - name: Install compatibility-with-php8-to-phpunit-7
        if: ${{ matrix.php == '8.0' }}
        run: |
          composer config --unset platform
          composer config repositories.0 '{"type":"vcs","url":"https://github.com/woocommerce/phpunit.git"}'
          composer require --dev --update-with-all-dependencies --ignore-platform-req=php 'phpunit/phpunit:dev-add-compatibility-with-php8-to-phpunit-7 as 7.5'
```

https://github.com/szepeviktor/woocommerce-germanized/blob/a31949e3bc5a36dc216558b7c8f22d51a2e7582b/.github/workflows/test.yml#L36-L46

**Pull request closed without merging**
